In [8]:
import numpy as np
import pandas as pd

df = pd.read_csv('HR_comma_sep.csv')
#reading the data from the HR_comma_sep.csv file and storing it in df

x = df[['satisfaction_level','last_evaluation','number_project','average_montly_hours','time_spend_company','Work_accident','salary']]
#getting features from df
features = np.array(x)

y = df[['left']]
lables = np.array(y)
#lables will be if the employee left the company or not

df.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years  sales  \
0                   3              0     1                      0  sales   
1                   6              0     1                      0  sales   
2                   4              0     1                      0  sales   
3                   5              0     1                      0  sales   
4                   3              0     1                      0  sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [9]:
features[0]


array([0.38, 0.53, 2, 157, 3, 0, 'low'], dtype=object)

In [22]:
#changing the salary from string to numbers
#'low' = 1
#'medium' = 2
#'high' = 3

for x in features:
    if(x[6]=='low'):#6 because salary is the 7th element in it
        x[6] = 1
    elif(x[6]=='medium'):
        x[6] = 2
    elif(x[6]=='high'):
        x[6] = 3
    
features[0]

array([0.38, 0.53, 2, 157, 3, 0, 1], dtype=object)

In [11]:
from sklearn.cross_validation import train_test_split
x_train,x_test,y_train,y_test = train_test_split(features,lables,test_size = 0.4, random_state = 42)
len(x_train)

8999

In [25]:
#Support Vector Machine(SVM)

from sklearn.svm import SVC
clf = SVC()
print(clf.fit(x_train,y_train))

pred = clf.predict(x_test)
print('prediction is', pred)

print("acc = ",clf.score(x_test,y_test))

/home/mak/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
prediction is [0 0 0 ... 1 0 0]
acc =  0.9531666666666667


In [13]:
c = 0
for x in range(0,len(y_test)):
    if(pred[x]==y_test[x]):
        c = c+1

print(len(y_test)," = y_test")
print(c," = c")

6000  = y_test
5719  = c


In [14]:
from sklearn import metrics
print("Precision score = ",metrics.precision_score(y_test,pred))
print("Recall score = ",metrics.recall_score(y_test,pred))

Precision score =  0.8902691511387164
Recall score =  0.9135977337110481


In [15]:

#Decision Tress Classifire

from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(splitter='random')
print(clf.fit(x_train,y_train))
pred = clf.predict(x_test)
print(pred)

print("acc = ",clf.score(x_test,y_test))

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='random')
[0 0 0 ... 1 0 0]
acc =  0.9756666666666667


In [16]:
c = 0
for x in range(0,len(y_test)):
    if(pred[x]==y_test[x]):
        c = c+1

print(len(y_test)," = y_test")
print(c," = c")

6000  = y_test
5854  = c


In [17]:
from sklearn import metrics
print("Precision score = ",metrics.precision_score(y_test,pred))
print("Recall score = ",metrics.recall_score(y_test,pred))

Precision score =  0.9414225941422594
Recall score =  0.9560906515580736
